### ISSUE TITLE
sbasm exit code = 0 when error is not fatal?

### ISSUE THREAD

**Issue by wil-low** [sbprojects/sbasm3#12]
$ ~/program/sbasm3/sbasm collatz.asm

SB-Cross Assembler version 3.03.07
Please visit www.sbprojects.net for a complete description.

Assembling....

Pass one
Loaded scmp overlay version 3.02.00
Source file: collatz.asm

*** Error: Bad Operand
    107                 DLY             Delay(2)

1 Error found during assembly.
0 Warnings found during assembly.

$ echo $?
0

ERRLVL_PASS1 = 1    # Errors found during pass 1
ERRLVL_PASS2 = 2    # Errors found during pass 2
are never used

**Comment by sbprojects** [comment]
This issue is as of version 3.03.10 now. Thank you for reporting.
