### ISSUE TITLE
How to do ? Escaping characters in macros ?

### ISSUE THREAD

**Issue by feldti** [sbprojects/sbasm3#3]
```
	.CR		Z180
    .EF     macrotest.err
    .LF     macrotest.lst

head    .MA   name
        .AS "]1"
        .EM

    >head   "Marten"
    >head  "Marten\"Feldtmann"
        .EN
```

**Comment by sbprojects** [comment]
The SB-Assembler doesn't understand the concept of escaping characters.

There are few ways around this though.
One way is to change the Macro definition to not use the double quote as delimiter and use the single delimiter in the expansion call:
head  .MA  name
          .AS /]1/
          .EM
  >head 'Marten"Feldtmann'
Note that the double quote is not present in the definition part nor in the expansion part of the macro.

Another way of achieving this is to avoid using the delimiters in the definition and use your own set of delimiters in the expansion:
head   .MA  name
          .AS ]1
          .EM

   >head   '/Marten"Feldtmann/'
Here the / is the delimiter around the string, whereas the single quotes are used to combine the entire string into one parameter.

And yet another way of writing this is substitute the double quote by an immediate value:
head  .MA  name
         .AS  ]1
         .EM

   >head "/Marten/,#$22,/Feldtmann/"
Again I use the / as delimiter for both halves of the string, and $22 is the ASCII value for the double quote.

A good thing to remember about macro parameters is that the text is pasted literally into the expanding macro, excluding the opening and closing double or single quotes.

**Comment by feldti** [comment]
Ok, I was looking to handle a larger Z180 FORTH assembler source text and did not want to change the Z180 assembler source - therefore I changed the sbasm  source code at two locations:

In direct.py I changed the DirAS function to handle a "\" character:

```
 while dec.Asm.Parse_Pointer < len(dec.Asm.Parse_Line) - 1:
                char = assem.NowChar(True)
                if char == "\\":
                    char = assem.NowChar(True)
                else:
                    if char == delimit:
                        break
                count = count + 1
                characters.append(ord(char) | negasc)
            if char != delimit:
                # End of line found without delimiter
                errors.DoError('strterm', False)
                break
```
In "macros.py" I changed the GetOneParameter() function:

```
        while assem.NowChar() != endmark:
            singleChar = assem.NowChar(True)
            if singleChar == "\\":
                parameter = parameter + singleChar
                singleChar = assem.NowChar(True)
            # Get parameter until end mark
            parameter = parameter + singleChar
        assem.IncParsePointer()     # Increment past endmark
```
And now I could assemble the Z180 FORTH code source

**Comment by sbprojects** [comment]
Good show. I will implement this within a couple of days, with a small change. The escaping will not be allowed if the string is delimited by a \ for that may break existing code. So I will change the if char == "\\" statement a bit.
And I'll have to make an update for the user manual. Will be done before the end of the year.
