### ISSUE TITLE
Z180 overlay - some mnemonics are wrong

### ISSUE THREAD

**Issue by feldti** [sbprojects/sbasm3#4]
In the Z180 overlay the INO and OUTO commands are available, but they should be named IN0 and OUT0.

This can be changed in the files "crz80.py" and  "crz180.py". Look for occurences of OUTO and INO and add/change the corresponding code to cover IN0 and OUT0

**Comment by sbprojects** [comment]
Thanks for spotting that one. I will correct it in a couple of days.
