### ISSUE TITLE
Expression should have more power

### ISSUE THREAD

**Issue by feldti** [sbprojects/sbasm3#5]
I would like to see, that the expression could at least use "(" and ")" to make more complex calculation.
I mainly define textual constants and use these constants in my code, but very often I have to make calculation based on several constants with arithmetics like "*4", "*128" etc ...

**Comment by sbprojects** [comment]
Personally I have never really needed more expression power. Often you can get around the limitations by rearranging the formula or breaking it up in 2 or more parts. I find it too complicated to add preference and parentheses for all situations to justify the work required to make it universal. And above that it could break existing assembly code.

On the other hand, while thinking through the possibilities, I could add more power for constants and variables only, so for .EQ and .SE directives only. And to avoid backward compatibility problems I could automatically switch to the more advanced way of parsing expressions by using a pair of opening and closing parentheses.

So 1+2\*3 would be 9 (old situation for compatibility)
While (1+2\*3) would be 7 (new situation)

And 2*(3+4) would give an error (old situation, never occurring in old code)
While (2*(3+4)) would give 14 (new situation)

I will think about it and see what I can do. No promises though.
